name: build
on: [push, pull_request]
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Get dependencies
      run: make deps
    - name: Build source
      run: make build
    - name: Test source
      run: make test FLAGS='-v -count=1 -coverprofile /tmp/cover.out -shuffle=on'
    - name: Vet source
      run: make vet
    - name: Upload code coverage
      uses: codecov/codecov-action@v3
      with:
        files: /tmp/cover.out

  security_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Run gosec
      uses: securego/gosec@master
      with:
        args: --tests ./...
